# Generated by Django 5.0.3 on 2024-03-18 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musician',
            options={'verbose_name': 'Музыкант', 'verbose_name_plural': 'Музыканты'},
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='psevdonym',
            new_name='pseudonym',
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.ImageField(blank=True, upload_to='images')),
                ('date', models.DateField()),
                ('author', models.ForeignKey(on_delete=models.SET('deleted'), related_name='songs', to='main.musician')),
                ('feat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feats', to='main.musician')),
            ],
        ),
    ]
